import type { Metadata } from "next";
import { FadeIn } from "@/components/motion/fade-in";

export const metadata: Metadata = {
  title: "Terms of Service | PlanForge",
  description: "PlanForge terms of service — acceptable use, subscription terms, and liability.",
  robots: { index: true, follow: true },
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="bg-background py-16 lg:py-24">
      <FadeIn className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        <h1
          className="text-3xl md:text-4xl font-black text-foreground mb-2"
          style={{ fontFamily: "var(--font-display)" }}
        >
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 2026</p>

        <div className="prose prose-sm prose-neutral dark:prose-invert max-w-none space-y-8 text-foreground/80">
          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">1. Acceptance</h2>
            <p>
              By using PlanForge you agree to these terms. If you do not agree, do not use the
              service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">2. Service description</h2>
            <p>
              PlanForge is a web-based floor plan generation tool for residential construction in
              India. Generated plans are indicative templates and must be reviewed and stamped by a
              licensed architect or civil engineer before submission to any municipal authority.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">3. Subscriptions & payments</h2>
            <p>
              Paid plans are billed monthly. You may cancel at any time; access continues until the
              end of the billing period. Refunds are not issued for partial months. Credit packs do
              not expire and are non-refundable after use.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">4. Acceptable use</h2>
            <p>
              You may not use PlanForge to generate plans for illegal construction, circumvent
              building regulations, or resell generated outputs as your own proprietary software.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">5. Disclaimer</h2>
            <p>
              Plans generated by PlanForge are provided as-is for reference. PlanForge does not
              guarantee compliance with all local by-laws, RERA requirements, or site-specific
              conditions. Always verify with a licensed professional.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">6. Limitation of liability</h2>
            <p>
              PlanForge's liability is limited to the subscription fees paid in the 3 months
              preceding any claim. We are not liable for consequential damages arising from use of
              generated floor plans.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">7. Governing law</h2>
            <p>
              These terms are governed by the laws of India. Disputes shall be resolved in Trichy,
              Tamil Nadu.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">Contact</h2>
            <p>
              For legal enquiries, email{" "}
              <a href="mailto:legal@planforge.in" className="text-primary hover:underline">
                legal@planforge.in
              </a>
              .
            </p>
          </section>
        </div>
      </FadeIn>
    </div>
  );
}
