"""Unified title-block renderer shared by both PDF generators.

Every page of the standard PDF (`pdf.py`) and the approval PDF
(`approval_pdf.py`) draws the same title-block look through
:func:`draw_title_block`: a full-width bordered strip made of a single row of
labelled field cells (dark header band + value below), an optional stack of
centred subtitle lines, an optional signature/seal strip for submission pages,
and a footer credit.  Callers differ only in the field list and the block
height (`top`), so the three previously divergent renderers now read alike.
"""

from __future__ import annotations

from reportlab.lib.colors import HexColor, white
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfgen import canvas

BRAND = "Generated by PlanForge · NBC 2016 Compliant"

_HEADER_H = 18.0  # dark label band height (points)
_FIELD_ROW_H = 40.0  # field cell zone height (label band + value)


def draw_title_block(
    c: canvas.Canvas,
    page_w: float,
    top: float,
    fields: list[tuple[str, str]],
    *,
    subtitle_lines: list[str] | None = None,
    signature: bool = False,
    footer: str = BRAND,
) -> None:
    """Render the shared title block from ``y=0`` up to ``y=top``.

    Parameters
    ----------
    c              : ReportLab canvas.
    page_w         : page width in points (block spans the full width).
    top            : y of the block's top edge (its overall height).
    fields         : ``(label, value)`` pairs laid out as one row of cells.
    subtitle_lines : centred lines drawn just below the field cells.
    signature      : draw the architect-signature + official-seal strip
                     (municipality submission pages).
    footer         : bottom-right credit line.
    """
    if not fields:
        raise ValueError("draw_title_block requires at least one field")

    # Outer border + heavy separator between the block and the drawing above.
    c.setStrokeColor(HexColor("#000000"))
    c.setLineWidth(1.0)
    c.rect(0, 0, page_w, top, fill=0, stroke=1)
    c.setLineWidth(1.5)
    c.line(0, top, page_w, top)

    _draw_field_cells(c, page_w, top, fields)

    # Separator under the field row.
    c.setStrokeColor(HexColor("#000000"))
    c.setLineWidth(0.5)
    c.line(0, top - _FIELD_ROW_H, page_w, top - _FIELD_ROW_H)

    body_top = top - _FIELD_ROW_H
    if subtitle_lines:
        c.setFillColor(HexColor("#000000"))
        c.setFont("Helvetica-Bold", 6.5)
        ty = body_top - 10
        for line in subtitle_lines:
            c.drawCentredString(page_w / 2, ty, line)
            ty -= 10
        body_top = ty + 4

    if signature:
        _draw_signature_strip(c, page_w, body_top - 6)

    c.setFillColor(HexColor("#888888"))
    c.setFont("Helvetica", 5)
    c.drawRightString(page_w - 4, 4, footer)


def _draw_field_cells(
    c: canvas.Canvas, page_w: float, top: float, fields: list[tuple[str, str]]
) -> None:
    col_w = page_w / len(fields)
    for i, (label, value) in enumerate(fields):
        cx = col_w * i + col_w / 2
        cell_x = col_w * i

        c.setFillColor(HexColor("#222222"))
        c.rect(cell_x, top - _HEADER_H, col_w, _HEADER_H, fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont("Helvetica-Bold", 6)
        c.drawCentredString(cx, top - 12, label)

        c.setFillColor(HexColor("#000000"))
        avail = col_w - 6
        vfont = 7.5
        while (
            vfont > 5.0
            and pdfmetrics.stringWidth(value, "Helvetica-Bold", vfont) > avail
        ):
            vfont -= 0.5
        if pdfmetrics.stringWidth(value, "Helvetica-Bold", vfont) <= avail:
            c.setFont("Helvetica-Bold", vfont)
            c.drawCentredString(cx, top - 34, value)
        else:
            line1, line2 = "", ""
            for word in value.split():
                cand = (line1 + " " + word).strip()
                if pdfmetrics.stringWidth(cand, "Helvetica-Bold", 5.5) <= avail:
                    line1 = cand
                else:
                    line2 = (line2 + " " + word).strip()
            c.setFont("Helvetica-Bold", 5.5)
            c.drawCentredString(cx, top - 30, line1)
            c.drawCentredString(cx, top - 37, line2)

        if i > 0:
            c.setStrokeColor(HexColor("#000000"))
            c.setLineWidth(0.5)
            c.line(cell_x, 0, cell_x, top)


def _draw_signature_strip(
    c: canvas.Canvas, page_w: float, top_y: float, bottom_y: float = 12.0
) -> None:
    """Architect-signature (left) + official-seal (right) boxes."""
    if top_y - bottom_y < 24:
        return
    half = page_w / 2
    height = top_y - bottom_y

    # Signature box (left half).
    c.setStrokeColor(HexColor("#CCCCCC"))
    c.setLineWidth(0.5)
    c.rect(0, bottom_y, half, height, fill=0, stroke=1)
    c.setFillColor(HexColor("#555555"))
    c.setFont("Helvetica", 7)
    c.drawString(6, top_y - 12, "Signature of Architect/Engineer:")
    c.setStrokeColor(HexColor("#808080"))
    line_y = bottom_y + height * 0.4
    c.line(8, line_y, half - 8, line_y)
    c.setFillColor(HexColor("#808080"))
    c.setFont("Helvetica-Oblique", 6)
    c.drawCentredString(half / 2, line_y - 9, "(Authorised Signatory)")

    # Seal box (right half).
    c.setStrokeColor(HexColor("#CCCCCC"))
    c.setLineWidth(0.5)
    c.rect(half, bottom_y, half, height, fill=0, stroke=1)
    seal_cx = half + half / 2
    seal_cy = bottom_y + height / 2
    seal_r = min(height / 2 - 4, half / 3)
    c.setStrokeColor(HexColor("#CCCCCC"))
    c.setLineWidth(0.75)
    c.circle(seal_cx, seal_cy, seal_r, fill=0, stroke=1)
    c.setStrokeColor(HexColor("#EBEBEB"))
    c.circle(seal_cx, seal_cy, seal_r * 0.8, fill=0, stroke=1)
    c.setFillColor(HexColor("#CCCCCC"))
    c.setFont("Helvetica", 6)
    c.drawCentredString(seal_cx, seal_cy + 3, "SEAL")
    c.drawCentredString(seal_cx, seal_cy - 6, "(Office Stamp)")
    c.setFillColor(HexColor("#555555"))
    c.setFont("Helvetica", 7)
    c.drawString(half + 6, top_y - 12, "Official Seal:")
